name: dmdreader
on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  version:
    name: Detect version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: |
          TAG=`cat version.txt`
          echo "${TAG}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - name: Check git tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          GIT_TAG="${GITHUB_REF#refs/tags/}"
          EXPECTED_TAG="v${{ steps.version.outputs.tag }}"
          if [[ "${GIT_TAG}" != "${EXPECTED_TAG}" ]]; then
            echo "Error: Git tag (${GIT_TAG}) does not match version from version.txt (v${{ steps.version.outputs.tag }})"
            exit 1
          fi

  build:
    name: Build dmdreader
    runs-on: ${{ matrix.os }}
    needs: [ version ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Checkout pico-sdk
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          ref: 2.1.1
          fetch-depth: 1
      - if: (matrix.platform == 'linux' && matrix.arch == 'x64')
        run: sudo apt install gdb-multiarch cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib cmake
      - if: (!(matrix.platform == 'linux' && matrix.arch == 'aarch64'))
        run: scripts/compile.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dmdreader-${{ needs.version.outputs.tag }}
          path: |
            dmdreader.elf
            dmdreader.uf2
            version.txt

  post-build:
    runs-on: ubuntu-latest
    needs: [ version, build ]
    name: Release
    steps:
      - uses: actions/download-artifact@v4
      - name: Package
        if: startsWith(github.ref, 'refs/tags/v')
        run: zip dmdreader-${{ needs.version.outputs.tag }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: |
            dmdreader-${{ needs.version.outputs.tag }}.zip
